name: Build Brus-16

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: libsdl-org/setup-sdl@main
        with:
          version: 3-head
          install-linux-dependencies: true
      - run: make emu
      - uses: actions/upload-artifact@main
        with:
          name: brus16_linux
          path: brus16

  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          sudo apt-get install -y mingw-w64
          wget https://github.com/libsdl-org/SDL/releases/download/prerelease-3.3.4/SDL3-devel-3.3.4-mingw.tar.gz
          tar -xzf SDL3-devel-3.3.4-mingw.tar.gz     
      - run: make emu OS=Windows_NT CC=x86_64-w64-mingw32-gcc SDL=SDL3-3.3.4/x86_64-w64-mingw32      
      - run: |
          mkdir release
          mv brus16.exe release/
          cp SDL3-3.3.4/x86_64-w64-mingw32/bin/SDL3.dll release/          
      - uses: actions/upload-artifact@main
        with:
          name: brus16_windows
          path: release/
